services:
  api:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db, redis]
    command: >
      bash -lc "alembic upgrade head && uvicorn app.main:app --host ${API_HOST:-0.0.0.0} --port ${API_PORT:-8000}"
  worker:
    build: .
    env_file: .env
    depends_on: [db, redis]
    command: celery -A app.jobs.celery_app.celery_app worker --loglevel=INFO
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pfa
    ports: ["5432:5432"]
    volumes: [pfa_pg:/var/lib/postgresql/data]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  pfa_pg:
